# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
<<<<<<< HEAD

from ._models import AppComponent
from ._models import ArtifactsContainerInfo
from ._models import AutoStopCriteria
from ._models import CertificateMetadata
from ._models import DimensionFilter
from ._models import DimensionValue
from ._models import DimensionValueList
from ._models import ErrorDetails
from ._models import FunctionFlexConsumptionResourceConfiguration
from ._models import FunctionFlexConsumptionTargetResourceConfigurations
from ._models import LoadTestConfiguration
from ._models import MetricAvailability
from ._models import MetricDefinition
from ._models import MetricDefinitionCollection
from ._models import MetricNamespace
from ._models import MetricNamespaceCollection
from ._models import MetricRequestPayload
from ._models import MetricValue
from ._models import NameAndDesc
from ._models import OptionalLoadTestConfig
from ._models import PassFailCriteria
from ._models import PassFailMetric
from ._models import RegionalConfiguration
from ._models import ResourceMetric
from ._models import Secret
from ._models import TargetResourceConfigurations
from ._models import Test
from ._models import TestAppComponents
from ._models import TestFileInfo
from ._models import TestInputArtifacts
from ._models import TestProfile
from ._models import TestProfileRun
from ._models import TestProfileRunRecommendation
from ._models import TestRun
from ._models import TestRunAppComponents
from ._models import TestRunArtifacts
from ._models import TestRunDetail
from ._models import TestRunFileInfo
from ._models import TestRunInputArtifacts
from ._models import TestRunOutputArtifacts
from ._models import TestRunServerMetricConfig
from ._models import TestRunStatistics
from ._models import TestServerMetricConfig
from ._models import TimeSeriesElement

from ._enums import AggregationType
from ._enums import CertificateType
from ._enums import FileStatus
from ._enums import FileType
from ._enums import MetricUnit
from ._enums import PFAction
from ._enums import PFAgFunc
from ._enums import PFMetrics
from ._enums import PFResult
from ._enums import PFTestResult
from ._enums import RecommendationCategory
from ._enums import RequestDataLevel
from ._enums import ResourceKind
from ._enums import SecretType
from ._enums import Status
from ._enums import TestKind
from ._enums import TestProfileRunStatus
from ._enums import TimeGrain
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
=======
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import


from ._models import (  # type: ignore
    AppComponent,
    ArtifactsContainerInfo,
    AutoStopCriteria,
    CertificateMetadata,
    DailyRecurrence,
    DimensionFilter,
    DimensionValue,
    ErrorDetails,
    FunctionFlexConsumptionResourceConfiguration,
    FunctionFlexConsumptionTargetResourceConfigurations,
    HourlyRecurrence,
    LoadTestConfiguration,
    MetricAvailability,
    MetricDefinition,
    MetricDefinitionCollection,
    MetricNamespace,
    MetricNamespaceCollection,
    MetricRequestPayload,
    MetricValue,
    MonthlyRecurrenceByDates,
    MonthlyRecurrenceByWeekDays,
    NameAndDescription,
    NotificationRule,
    OperationStatus,
    OptionalLoadTestConfiguration,
    PassFailCriteria,
    PassFailMetric,
    PassFailServerMetric,
    Recurrence,
    RecurrenceEnd,
    RecurrenceStatus,
    RecurrenceWithCron,
    RegionalConfiguration,
    ResourceMetric,
    ScheduleTestsTrigger,
    Secret,
    StateDetails,
    TargetResourceConfigurations,
    Test,
    TestAppComponents,
    TestFileInfo,
    TestInputArtifacts,
    TestProfile,
    TestProfileRun,
    TestProfileRunRecommendation,
    TestRun,
    TestRunAppComponents,
    TestRunArtifacts,
    TestRunDetail,
    TestRunEndedEventCondition,
    TestRunEndedNotificationEventFilter,
    TestRunFileInfo,
    TestRunInputArtifacts,
    TestRunOutputArtifacts,
    TestRunServerMetricsConfiguration,
    TestRunStartedNotificationEventFilter,
    TestRunStatistics,
    TestServerMetricsConfiguration,
    TestsNotificationEventFilter,
    TestsNotificationRule,
    TimeSeriesElement,
    Trigger,
    TriggerCompletedNotificationEventFilter,
    TriggerDisabledNotificationEventFilter,
    WeeklyRecurrence,
)

from ._enums import (  # type: ignore
    Aggregation,
    CertificateType,
    CreatedByType,
    FileType,
    FileValidationStatus,
    Frequency,
    ManagedIdentityType,
    MetricUnit,
    NotificationEventType,
    NotificationScopeType,
    OperationKind,
    OperationState,
    PFMetrics,
    PassFailAction,
    PassFailAggregationFunction,
    PassFailResult,
    PassFailTestResult,
    RecommendationCategory,
    RequestDataLevel,
    ResourceKind,
    SecretType,
    TestKind,
    TestProfileRunStatus,
    TestRunStatus,
    TimeGrain,
    TriggerState,
    TriggerType,
    WeekDays,
)
from ._patch import __all__ as _patch_all
from ._patch import *
>>>>>>> upstream/main
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AppComponent",
    "ArtifactsContainerInfo",
    "AutoStopCriteria",
    "CertificateMetadata",
<<<<<<< HEAD
    "DimensionFilter",
    "DimensionValue",
    "DimensionValueList",
    "ErrorDetails",
    "FunctionFlexConsumptionResourceConfiguration",
    "FunctionFlexConsumptionTargetResourceConfigurations",
=======
    "DailyRecurrence",
    "DimensionFilter",
    "DimensionValue",
    "ErrorDetails",
    "FunctionFlexConsumptionResourceConfiguration",
    "FunctionFlexConsumptionTargetResourceConfigurations",
    "HourlyRecurrence",
>>>>>>> upstream/main
    "LoadTestConfiguration",
    "MetricAvailability",
    "MetricDefinition",
    "MetricDefinitionCollection",
    "MetricNamespace",
    "MetricNamespaceCollection",
    "MetricRequestPayload",
    "MetricValue",
<<<<<<< HEAD
    "NameAndDesc",
    "OptionalLoadTestConfig",
    "PassFailCriteria",
    "PassFailMetric",
    "RegionalConfiguration",
    "ResourceMetric",
    "Secret",
=======
    "MonthlyRecurrenceByDates",
    "MonthlyRecurrenceByWeekDays",
    "NameAndDescription",
    "NotificationRule",
    "OperationStatus",
    "OptionalLoadTestConfiguration",
    "PassFailCriteria",
    "PassFailMetric",
    "PassFailServerMetric",
    "Recurrence",
    "RecurrenceEnd",
    "RecurrenceStatus",
    "RecurrenceWithCron",
    "RegionalConfiguration",
    "ResourceMetric",
    "ScheduleTestsTrigger",
    "Secret",
    "StateDetails",
>>>>>>> upstream/main
    "TargetResourceConfigurations",
    "Test",
    "TestAppComponents",
    "TestFileInfo",
    "TestInputArtifacts",
    "TestProfile",
    "TestProfileRun",
    "TestProfileRunRecommendation",
    "TestRun",
    "TestRunAppComponents",
    "TestRunArtifacts",
    "TestRunDetail",
<<<<<<< HEAD
    "TestRunFileInfo",
    "TestRunInputArtifacts",
    "TestRunOutputArtifacts",
    "TestRunServerMetricConfig",
    "TestRunStatistics",
    "TestServerMetricConfig",
    "TimeSeriesElement",
    "AggregationType",
    "CertificateType",
    "FileStatus",
    "FileType",
    "MetricUnit",
    "PFAction",
    "PFAgFunc",
    "PFMetrics",
    "PFResult",
    "PFTestResult",
=======
    "TestRunEndedEventCondition",
    "TestRunEndedNotificationEventFilter",
    "TestRunFileInfo",
    "TestRunInputArtifacts",
    "TestRunOutputArtifacts",
    "TestRunServerMetricsConfiguration",
    "TestRunStartedNotificationEventFilter",
    "TestRunStatistics",
    "TestServerMetricsConfiguration",
    "TestsNotificationEventFilter",
    "TestsNotificationRule",
    "TimeSeriesElement",
    "Trigger",
    "TriggerCompletedNotificationEventFilter",
    "TriggerDisabledNotificationEventFilter",
    "WeeklyRecurrence",
    "Aggregation",
    "CertificateType",
    "CreatedByType",
    "FileType",
    "FileValidationStatus",
    "Frequency",
    "ManagedIdentityType",
    "MetricUnit",
    "NotificationEventType",
    "NotificationScopeType",
    "OperationKind",
    "OperationState",
    "PFMetrics",
    "PassFailAction",
    "PassFailAggregationFunction",
    "PassFailResult",
    "PassFailTestResult",
>>>>>>> upstream/main
    "RecommendationCategory",
    "RequestDataLevel",
    "ResourceKind",
    "SecretType",
<<<<<<< HEAD
    "Status",
    "TestKind",
    "TestProfileRunStatus",
    "TimeGrain",
]
__all__.extend([p for p in _patch_all if p not in __all__])
=======
    "TestKind",
    "TestProfileRunStatus",
    "TestRunStatus",
    "TimeGrain",
    "TriggerState",
    "TriggerType",
    "WeekDays",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
>>>>>>> upstream/main
_patch_sdk()
