# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
<<<<<<< HEAD
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import TYPE_CHECKING

from azure.core.configuration import Configuration
=======
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any, TYPE_CHECKING, Union

from azure.core.credentials import AzureKeyCredential
>>>>>>> upstream/main
from azure.core.pipeline import policies

from ._version import VERSION

if TYPE_CHECKING:
<<<<<<< HEAD
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any

    from azure.core.credentials import TokenCredential


class QuantumClientConfiguration(Configuration):  # pylint: disable=too-many-instance-attributes
    """Configuration for QuantumClient.
=======
    from azure.core.credentials import TokenCredential


class ServicesClientConfiguration:  # pylint: disable=too-many-instance-attributes
    """Configuration for ServicesClient.
>>>>>>> upstream/main

    Note that all parameters used to create this instance are saved as instance
    attributes.

<<<<<<< HEAD
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: The Azure subscription ID. This is a GUID-formatted string (e.g.
     00000000-0000-0000-0000-000000000000).
    :type subscription_id: str
    :param resource_group_name: Name of an Azure resource group.
    :type resource_group_name: str
    :param workspace_name: Name of the workspace.
    :type workspace_name: str
=======
    :param region: The Azure region where the Azure Quantum Workspace is located. Required.
    :type region: str
    :param credential: Credential used to authenticate requests to the service. Is either a
     TokenCredential type or a AzureKeyCredential type. Required.
    :type credential: ~azure.core.credentials.TokenCredential or
     ~azure.core.credentials.AzureKeyCredential
    :param service_base_url: The Azure Quantum service base url. Default value is
     "quantum.azure.com".
    :type service_base_url: str
    :keyword api_version: The API version to use for this operation. Default value is
     "2024-10-01-preview". Note that overriding this default value may result in unsupported
     behavior.
    :paramtype api_version: str
>>>>>>> upstream/main
    """

    def __init__(
        self,
<<<<<<< HEAD
        credential,  # type: "TokenCredential"
        subscription_id,  # type: str
        resource_group_name,  # type: str
        workspace_name,  # type: str
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        super(QuantumClientConfiguration, self).__init__(**kwargs)
        if credential is None:
            raise ValueError("Parameter 'credential' must not be None.")
        if subscription_id is None:
            raise ValueError("Parameter 'subscription_id' must not be None.")
        if resource_group_name is None:
            raise ValueError("Parameter 'resource_group_name' must not be None.")
        if workspace_name is None:
            raise ValueError("Parameter 'workspace_name' must not be None.")

        self.credential = credential
        self.subscription_id = subscription_id
        self.resource_group_name = resource_group_name
        self.workspace_name = workspace_name
        self.credential_scopes = kwargs.pop('credential_scopes', ['https://quantum.microsoft.com/.default'])
        kwargs.setdefault('sdk_moniker', 'quantum/{}'.format(VERSION))
        self._configure(**kwargs)

    def _configure(
        self,
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        self.user_agent_policy = kwargs.get('user_agent_policy') or policies.UserAgentPolicy(**kwargs)
        self.headers_policy = kwargs.get('headers_policy') or policies.HeadersPolicy(**kwargs)
        self.proxy_policy = kwargs.get('proxy_policy') or policies.ProxyPolicy(**kwargs)
        self.logging_policy = kwargs.get('logging_policy') or policies.NetworkTraceLoggingPolicy(**kwargs)
        self.http_logging_policy = kwargs.get('http_logging_policy') or policies.HttpLoggingPolicy(**kwargs)
        self.retry_policy = kwargs.get('retry_policy') or policies.RetryPolicy(**kwargs)
        self.custom_hook_policy = kwargs.get('custom_hook_policy') or policies.CustomHookPolicy(**kwargs)
        self.redirect_policy = kwargs.get('redirect_policy') or policies.RedirectPolicy(**kwargs)
        self.authentication_policy = kwargs.get('authentication_policy')
        if self.credential and not self.authentication_policy:
            self.authentication_policy = policies.BearerTokenCredentialPolicy(self.credential, *self.credential_scopes, **kwargs)
=======
        region: str,
        credential: Union["TokenCredential", AzureKeyCredential],
        service_base_url: str = "quantum.azure.com",
        **kwargs: Any,
    ) -> None:
        api_version: str = kwargs.pop("api_version", "2024-10-01-preview")

        if region is None:
            raise ValueError("Parameter 'region' must not be None.")
        if credential is None:
            raise ValueError("Parameter 'credential' must not be None.")

        self.region = region
        self.credential = credential
        self.service_base_url = service_base_url
        self.api_version = api_version
        self.credential_scopes = kwargs.pop("credential_scopes", ["https://quantum.microsoft.com/.default"])
        kwargs.setdefault("sdk_moniker", "quantum/{}".format(VERSION))
        self.polling_interval = kwargs.get("polling_interval", 30)
        self._configure(**kwargs)

    def _infer_policy(self, **kwargs):
        if hasattr(self.credential, "get_token"):
            return policies.BearerTokenCredentialPolicy(self.credential, *self.credential_scopes, **kwargs)
        if isinstance(self.credential, AzureKeyCredential):
            return policies.AzureKeyCredentialPolicy(self.credential, "x-ms-quantum-api-key", **kwargs)
        raise TypeError(f"Unsupported credential: {self.credential}")

    def _configure(self, **kwargs: Any) -> None:
        self.user_agent_policy = kwargs.get("user_agent_policy") or policies.UserAgentPolicy(**kwargs)
        self.headers_policy = kwargs.get("headers_policy") or policies.HeadersPolicy(**kwargs)
        self.proxy_policy = kwargs.get("proxy_policy") or policies.ProxyPolicy(**kwargs)
        self.logging_policy = kwargs.get("logging_policy") or policies.NetworkTraceLoggingPolicy(**kwargs)
        self.http_logging_policy = kwargs.get("http_logging_policy") or policies.HttpLoggingPolicy(**kwargs)
        self.custom_hook_policy = kwargs.get("custom_hook_policy") or policies.CustomHookPolicy(**kwargs)
        self.redirect_policy = kwargs.get("redirect_policy") or policies.RedirectPolicy(**kwargs)
        self.retry_policy = kwargs.get("retry_policy") or policies.RetryPolicy(**kwargs)
        self.authentication_policy = kwargs.get("authentication_policy")
        if self.credential and not self.authentication_policy:
            self.authentication_policy = self._infer_policy(**kwargs)
>>>>>>> upstream/main
