# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
<<<<<<< HEAD

from ._operations import LoadTestAdministrationClientOperationsMixin
from ._operations import LoadTestRunClientOperationsMixin

from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
=======
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._operations import LoadTestAdministrationClientOperationsMixin  # type: ignore
from ._operations import LoadTestRunClientOperationsMixin  # type: ignore

from ._patch import __all__ as _patch_all
from ._patch import *
>>>>>>> upstream/main
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "LoadTestAdministrationClientOperationsMixin",
    "LoadTestRunClientOperationsMixin",
]
<<<<<<< HEAD
__all__.extend([p for p in _patch_all if p not in __all__])
=======
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
>>>>>>> upstream/main
_patch_sdk()
