# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
<<<<<<< HEAD
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.core.exceptions import HttpResponseError
import msrest.serialization


class BlobDetails(msrest.serialization.Model):
    """Blob details.

    All required parameters must be populated in order to send to Azure.

    :ivar container_name: Required. The container name.
=======
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

import datetime
from typing import Any, Dict, List, Literal, Mapping, Optional, TYPE_CHECKING, Union, overload

from azure.core.exceptions import ODataV4Format

from .. import _model_base
from .._model_base import rest_discriminator, rest_field
from ._enums import ItemType

if TYPE_CHECKING:
    from .. import models as _models


class BlobDetails(_model_base.Model):
    """The details (name and container) of the blob to store or download data.

    All required parameters must be populated in order to send to server.

    :ivar container_name: The container name. Required.
>>>>>>> upstream/main
    :vartype container_name: str
    :ivar blob_name: The blob name.
    :vartype blob_name: str
    """

<<<<<<< HEAD
    _validation = {
        'container_name': {'required': True},
    }

    _attribute_map = {
        'container_name': {'key': 'containerName', 'type': 'str'},
        'blob_name': {'key': 'blobName', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword container_name: Required. The container name.
        :paramtype container_name: str
        :keyword blob_name: The blob name.
        :paramtype blob_name: str
        """
        super(BlobDetails, self).__init__(**kwargs)
        self.container_name = kwargs['container_name']
        self.blob_name = kwargs.get('blob_name', None)


class CostEstimate(msrest.serialization.Model):
    """The job cost billed by the provider. The final cost on your bill might be slightly different due to added taxes and currency conversion rates.

    :ivar currency_code: The currency code.
    :vartype currency_code: str
    :ivar events: List of usage events.
    :vartype events: list[~azure.quantum._client.models.UsageEvent]
    :ivar estimated_total: The estimated total.
    :vartype estimated_total: float
    """

    _attribute_map = {
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'events': {'key': 'events', 'type': '[UsageEvent]'},
        'estimated_total': {'key': 'estimatedTotal', 'type': 'float'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword currency_code: The currency code.
        :paramtype currency_code: str
        :keyword events: List of usage events.
        :paramtype events: list[~azure.quantum._client.models.UsageEvent]
        :keyword estimated_total: The estimated total.
        :paramtype estimated_total: float
        """
        super(CostEstimate, self).__init__(**kwargs)
        self.currency_code = kwargs.get('currency_code', None)
        self.events = kwargs.get('events', None)
        self.estimated_total = kwargs.get('estimated_total', None)


class ErrorData(msrest.serialization.Model):
    """An error response from Azure.

    :ivar code: An identifier for the error. Codes are invariant and are intended to be consumed
     programmatically.
    :vartype code: str
    :ivar message: A message describing the error, intended to be suitable for displaying in a user
     interface.
    :vartype message: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword code: An identifier for the error. Codes are invariant and are intended to be consumed
         programmatically.
        :paramtype code: str
        :keyword message: A message describing the error, intended to be suitable for displaying in a
         user interface.
        :paramtype message: str
        """
        super(ErrorData, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.message = kwargs.get('message', None)


class JobDetails(msrest.serialization.Model):
    """Job details.

    Variables are only populated by the server, and will be ignored when sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar id: The job id.
    :vartype id: str
    :ivar name: The job name. Is not required for the name to be unique and it's only used for
     display purposes.
    :vartype name: str
    :ivar container_uri: Required. The blob container SAS uri, the container is used to host job
     data.
    :vartype container_uri: str
    :ivar input_data_uri: The input blob SAS uri, if specified, it will override the default input
     blob in the container.
    :vartype input_data_uri: str
    :ivar input_data_format: Required. The format of the input data.
    :vartype input_data_format: str
=======
    container_name: str = rest_field(name="containerName", visibility=["read", "create"])
    """The container name. Required."""
    blob_name: Optional[str] = rest_field(name="blobName", visibility=["read", "create"])
    """The blob name."""

    @overload
    def __init__(
        self,
        *,
        container_name: str,
        blob_name: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class CostEstimate(_model_base.Model):
    """The job cost billed by the provider. The final cost on your bill might be slightly different
    due to added taxes and currency conversion rates.


    :ivar currency_code: The currency code. Required.
    :vartype currency_code: str
    :ivar events: List of usage events.
    :vartype events: list[~azure.quantum.models.UsageEvent]
    :ivar estimated_total: The estimated total. Required.
    :vartype estimated_total: float
    """

    currency_code: str = rest_field(name="currencyCode")
    """The currency code. Required."""
    events: Optional[List["_models.UsageEvent"]] = rest_field()
    """List of usage events."""
    estimated_total: float = rest_field(name="estimatedTotal")
    """The estimated total. Required."""

    @overload
    def __init__(
        self,
        *,
        currency_code: str,
        estimated_total: float,
        events: Optional[List["_models.UsageEvent"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class InnerError(_model_base.Model):
    """An object containing more specific information about the error. As per Microsoft One API
    guidelines -
    https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.

    :ivar code: One of a server-defined set of error codes.
    :vartype code: str
    :ivar innererror: Inner error.
    :vartype innererror: ~azure.quantum.models.InnerError
    """

    code: Optional[str] = rest_field()
    """One of a server-defined set of error codes."""
    innererror: Optional["_models.InnerError"] = rest_field()
    """Inner error."""

    @overload
    def __init__(
        self,
        *,
        code: Optional[str] = None,
        innererror: Optional["_models.InnerError"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ItemDetails(_model_base.Model):
    """A workspace item.

    You probably want to use the sub-classes and not this class directly. Known sub-classes are:
    JobDetails, SessionDetails

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar id: Id of the item. Required.
    :vartype id: str
    :ivar name: The name of the item. It is not required for the name to be unique and it's only
     used for display purposes. Required.
    :vartype name: str
    :ivar provider_id: The unique identifier for the provider. Required.
    :vartype provider_id: str
    :ivar target: The target identifier to run the job. Required.
    :vartype target: str
    :ivar item_type: Type of the Quantum Workspace item. Required. Known values are: "Job" and
     "Session".
    :vartype item_type: str or ~azure.quantum.models.ItemType
    :ivar creation_time: The creation time of the item.
    :vartype creation_time: ~datetime.datetime
    :ivar begin_execution_time: The time when the item began execution.
    :vartype begin_execution_time: ~datetime.datetime
    :ivar end_execution_time: The time when the item finished execution.
    :vartype end_execution_time: ~datetime.datetime
    :ivar cost_estimate: Cost estimate.
    :vartype cost_estimate: ~azure.quantum.models.CostEstimate
    :ivar error_data: Error information.
    :vartype error_data: ~azure.quantum.models.WorkspaceItemError
    """

    __mapping__: Dict[str, _model_base.Model] = {}
    id: str = rest_field(visibility=["read"])
    """Id of the item. Required."""
    name: str = rest_field(visibility=["read", "create", "update"])
    """The name of the item. It is not required for the name to be unique and it's only used for
     display purposes. Required."""
    provider_id: str = rest_field(name="providerId", visibility=["read", "create"])
    """The unique identifier for the provider. Required."""
    target: str = rest_field(visibility=["read", "create"])
    """The target identifier to run the job. Required."""
    item_type: str = rest_discriminator(name="itemType", visibility=["read", "create"])
    """Type of the Quantum Workspace item. Required. Known values are: \"Job\" and \"Session\"."""
    creation_time: Optional[datetime.datetime] = rest_field(name="creationTime", visibility=["read"], format="rfc3339")
    """The creation time of the item."""
    begin_execution_time: Optional[datetime.datetime] = rest_field(
        name="beginExecutionTime", visibility=["read"], format="rfc3339"
    )
    """The time when the item began execution."""
    end_execution_time: Optional[datetime.datetime] = rest_field(
        name="endExecutionTime", visibility=["read"], format="rfc3339"
    )
    """The time when the item finished execution."""
    cost_estimate: Optional["_models.CostEstimate"] = rest_field(name="costEstimate", visibility=["read"])
    """Cost estimate."""
    error_data: Optional["_models.WorkspaceItemError"] = rest_field(name="errorData", visibility=["read"])
    """Error information."""

    @overload
    def __init__(
        self,
        *,
        name: str,
        provider_id: str,
        target: str,
        item_type: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class JobDetails(ItemDetails, discriminator="Job"):
    """A job to be run in the workspace.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar name: The name of the item. It is not required for the name to be unique and it's only
     used for display purposes. Required.
    :vartype name: str
    :ivar provider_id: The unique identifier for the provider. Required.
    :vartype provider_id: str
    :ivar target: The target identifier to run the job. Required.
    :vartype target: str
    :ivar creation_time: The creation time of the item.
    :vartype creation_time: ~datetime.datetime
    :ivar begin_execution_time: The time when the item began execution.
    :vartype begin_execution_time: ~datetime.datetime
    :ivar end_execution_time: The time when the item finished execution.
    :vartype end_execution_time: ~datetime.datetime
    :ivar cost_estimate: Cost estimate.
    :vartype cost_estimate: ~azure.quantum.models.CostEstimate
    :ivar error_data: Error information.
    :vartype error_data: ~azure.quantum.models.WorkspaceItemError
    :ivar id: Id of the job. Required.
    :vartype id: str
    :ivar item_type: Type of the Quantum Workspace item is Job. Required. A program, problem, or
     application submitted for processing.
    :vartype item_type: str or ~azure.quantum.models.JOB
    :ivar job_type: The type of job. Known values are: "Unknown", "QuantumComputing", and
     "Optimization".
    :vartype job_type: str or ~azure.quantum.models.JobType
    :ivar session_id: The ID of the session that the job is part of.
    :vartype session_id: str
    :ivar container_uri: The blob container SAS uri, the container is used to host job data.
     Required.
    :vartype container_uri: str
    :ivar input_data_uri: The input blob URI, if specified, it will override the default input blob
     in the container.
    :vartype input_data_uri: str
    :ivar input_data_format: The format of the input data.
    :vartype input_data_format: str
    :ivar status: The status of the job. Known values are: "Waiting", "Executing", "Succeeded",
     "Failed", and "Cancelled".
    :vartype status: str or ~azure.quantum.models.JobStatus
    :ivar metadata: The job metadata. Metadata provides client the ability to store client-specific
     information.
    :vartype metadata: any
    :ivar cancellation_time: The time when a job was successfully cancelled.
    :vartype cancellation_time: ~datetime.datetime
    :ivar tags: List of user-supplied tags associated with the job.
    :vartype tags: list[str]
    :ivar quantum_computing_data: Quantum computing data.
    :vartype quantum_computing_data: ~azure.quantum.models.QuantumComputingData
>>>>>>> upstream/main
    :ivar input_params: The input parameters for the job. JSON object used by the target solver. It
     is expected that the size of this object is small and only used to specify parameters for the
     execution target, not the input data.
    :vartype input_params: any
<<<<<<< HEAD
    :ivar provider_id: Required. The unique identifier for the provider.
    :vartype provider_id: str
    :ivar target: Required. The target identifier to run the job.
    :vartype target: str
    :ivar metadata: The job metadata. Metadata provides client the ability to store client-specific
     information.
    :vartype metadata: dict[str, str]
    :ivar output_data_uri: The output blob SAS uri. When a job finishes successfully, results will
     be uploaded to this blob.
    :vartype output_data_uri: str
    :ivar output_data_format: The format of the output data.
    :vartype output_data_format: str
    :ivar status: The job status. Known values are: "Waiting", "Executing", "Succeeded", "Failed",
     "Cancelled".
    :vartype status: str or ~azure.quantum._client.models.JobStatus
    :ivar creation_time: The creation time of the job.
    :vartype creation_time: ~datetime.datetime
    :ivar begin_execution_time: The time when the job began execution.
    :vartype begin_execution_time: ~datetime.datetime
    :ivar end_execution_time: The time when the job finished execution.
    :vartype end_execution_time: ~datetime.datetime
    :ivar cancellation_time: The time when a job was successfully cancelled.
    :vartype cancellation_time: ~datetime.datetime
    :ivar cost_estimate: The job cost billed by the provider. The final cost on your bill might be
     slightly different due to added taxes and currency conversion rates.
    :vartype cost_estimate: ~azure.quantum._client.models.CostEstimate
    :ivar error_data: The error data for the job. This is expected only when Status 'Failed'.
    :vartype error_data: ~azure.quantum._client.models.ErrorData
    :ivar tags: A set of tags. List of user-supplied tags associated with the job.
    :vartype tags: list[str]
    """

    _validation = {
        'container_uri': {'required': True},
        'input_data_format': {'required': True},
        'provider_id': {'required': True},
        'target': {'required': True},
        'status': {'readonly': True},
        'creation_time': {'readonly': True},
        'begin_execution_time': {'readonly': True},
        'end_execution_time': {'readonly': True},
        'cancellation_time': {'readonly': True},
        'cost_estimate': {'readonly': True},
        'error_data': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'container_uri': {'key': 'containerUri', 'type': 'str'},
        'input_data_uri': {'key': 'inputDataUri', 'type': 'str'},
        'input_data_format': {'key': 'inputDataFormat', 'type': 'str'},
        'input_params': {'key': 'inputParams', 'type': 'object'},
        'provider_id': {'key': 'providerId', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'metadata': {'key': 'metadata', 'type': '{str}'},
        'output_data_uri': {'key': 'outputDataUri', 'type': 'str'},
        'output_data_format': {'key': 'outputDataFormat', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'creation_time': {'key': 'creationTime', 'type': 'iso-8601'},
        'begin_execution_time': {'key': 'beginExecutionTime', 'type': 'iso-8601'},
        'end_execution_time': {'key': 'endExecutionTime', 'type': 'iso-8601'},
        'cancellation_time': {'key': 'cancellationTime', 'type': 'iso-8601'},
        'cost_estimate': {'key': 'costEstimate', 'type': 'CostEstimate'},
        'error_data': {'key': 'errorData', 'type': 'ErrorData'},
        'tags': {'key': 'tags', 'type': '[str]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword id: The job id.
        :paramtype id: str
        :keyword name: The job name. Is not required for the name to be unique and it's only used for
         display purposes.
        :paramtype name: str
        :keyword container_uri: Required. The blob container SAS uri, the container is used to host job
         data.
        :paramtype container_uri: str
        :keyword input_data_uri: The input blob SAS uri, if specified, it will override the default
         input blob in the container.
        :paramtype input_data_uri: str
        :keyword input_data_format: Required. The format of the input data.
        :paramtype input_data_format: str
        :keyword input_params: The input parameters for the job. JSON object used by the target solver.
         It is expected that the size of this object is small and only used to specify parameters for
         the execution target, not the input data.
        :paramtype input_params: any
        :keyword provider_id: Required. The unique identifier for the provider.
        :paramtype provider_id: str
        :keyword target: Required. The target identifier to run the job.
        :paramtype target: str
        :keyword metadata: The job metadata. Metadata provides client the ability to store
         client-specific information.
        :paramtype metadata: dict[str, str]
        :keyword output_data_uri: The output blob SAS uri. When a job finishes successfully, results
         will be uploaded to this blob.
        :paramtype output_data_uri: str
        :keyword output_data_format: The format of the output data.
        :paramtype output_data_format: str
        :keyword tags: A set of tags. List of user-supplied tags associated with the job.
        :paramtype tags: list[str]
        """
        super(JobDetails, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.container_uri = kwargs['container_uri']
        self.input_data_uri = kwargs.get('input_data_uri', None)
        self.input_data_format = kwargs['input_data_format']
        self.input_params = kwargs.get('input_params', None)
        self.provider_id = kwargs['provider_id']
        self.target = kwargs['target']
        self.metadata = kwargs.get('metadata', None)
        self.output_data_uri = kwargs.get('output_data_uri', None)
        self.output_data_format = kwargs.get('output_data_format', None)
        self.status = None
        self.creation_time = None
        self.begin_execution_time = None
        self.end_execution_time = None
        self.cancellation_time = None
        self.cost_estimate = None
        self.error_data = None
        self.tags = kwargs.get('tags', None)


class JobDetailsList(msrest.serialization.Model):
    """List of job details.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar value:
    :vartype value: list[~azure.quantum._client.models.JobDetails]
    :ivar count: Total records count number.
    :vartype count: long
    :ivar next_link: Link to the next page of results.
    :vartype next_link: str
    """

    _validation = {
        'value': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': '[JobDetails]'},
        'count': {'key': 'count', 'type': 'long'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword count: Total records count number.
        :paramtype count: long
        """
        super(JobDetailsList, self).__init__(**kwargs)
        self.value = None
        self.count = kwargs.get('count', None)
        self.next_link = None


class JsonPatchDocument(msrest.serialization.Model):
    """A JSONPatch document as defined by RFC 6902.

    All required parameters must be populated in order to send to Azure.

    :ivar op: Required. The operation to be performed. Known values are: "add", "remove",
     "replace", "move", "copy", "test".
    :vartype op: str or ~azure.quantum._client.models.JsonPatchOperation
    :ivar path: Required. A JSON-Pointer.
=======
    :ivar output_data_uri: The output blob uri. When a job finishes successfully, results will be
     uploaded to this blob.
    :vartype output_data_uri: str
    :ivar output_data_format: The format of the output data.
    :vartype output_data_format: str
    """

    item_type: Literal[ItemType.JOB] = rest_discriminator(name="itemType", visibility=["read", "create"])  # type: ignore # pylint: disable=line-too-long
    """Type of the Quantum Workspace item is Job. Required. A program, problem, or application
     submitted for processing."""
    job_type: Optional[Union[str, "_models.JobType"]] = rest_field(name="jobType", visibility=["read", "create"])
    """The type of job. Known values are: \"Unknown\", \"QuantumComputing\", and \"Optimization\"."""
    session_id: Optional[str] = rest_field(name="sessionId", visibility=["read", "create"])
    """The ID of the session that the job is part of."""
    container_uri: str = rest_field(name="containerUri", visibility=["read", "create"])
    """The blob container SAS uri, the container is used to host job data. Required."""
    input_data_uri: Optional[str] = rest_field(name="inputDataUri", visibility=["read", "create"])
    """The input blob URI, if specified, it will override the default input blob in the container."""
    input_data_format: Optional[str] = rest_field(name="inputDataFormat", visibility=["read", "create"])
    """The format of the input data."""
    status: Optional[Union[str, "_models.JobStatus"]] = rest_field(visibility=["read"])
    """The status of the job. Known values are: \"Waiting\", \"Executing\", \"Succeeded\", \"Failed\",
     and \"Cancelled\"."""
    metadata: Optional[Any] = rest_field(visibility=["read", "create", "update"])
    """The job metadata. Metadata provides client the ability to store client-specific information."""
    cancellation_time: Optional[datetime.datetime] = rest_field(
        name="cancellationTime", visibility=["read"], format="rfc3339"
    )
    """The time when a job was successfully cancelled."""
    tags: Optional[List[str]] = rest_field(visibility=["read", "create", "update"])
    """List of user-supplied tags associated with the job."""
    quantum_computing_data: Optional["_models.QuantumComputingData"] = rest_field(
        name="quantumComputingData", visibility=["read"]
    )
    """Quantum computing data."""
    input_params: Optional[Any] = rest_field(name="inputParams", visibility=["read", "create"])
    """The input parameters for the job. JSON object used by the target solver. It is expected that
     the size of this object is small and only used to specify parameters for the execution target,
     not the input data."""
    output_data_uri: Optional[str] = rest_field(name="outputDataUri", visibility=["read", "create"])
    """The output blob uri. When a job finishes successfully, results will be uploaded to this blob."""
    output_data_format: Optional[str] = rest_field(name="outputDataFormat", visibility=["read", "create"])
    """The format of the output data."""

    @overload
    def __init__(
        self,
        *,
        name: str,
        provider_id: str,
        target: str,
        container_uri: str,
        job_type: Optional[Union[str, "_models.JobType"]] = None,
        session_id: Optional[str] = None,
        input_data_uri: Optional[str] = None,
        input_data_format: Optional[str] = None,
        metadata: Optional[Any] = None,
        tags: Optional[List[str]] = None,
        input_params: Optional[Any] = None,
        output_data_uri: Optional[str] = None,
        output_data_format: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, item_type=ItemType.JOB, **kwargs)


class JsonPatchObject(_model_base.Model):
    """A JSONPatch object as defined by RFC 6902.

    All required parameters must be populated in order to send to server.

    :ivar operation: The operation to be performed. Required. Known values are: "add", "remove",
     "replace", "move", "copy", and "test".
    :vartype operation: str or ~azure.quantum.models.JsonPatchOperation
    :ivar path: A JSON-Pointer. Required.
>>>>>>> upstream/main
    :vartype path: str
    :ivar value: A value to be used in the operation on the path.
    :vartype value: any
    :ivar from_property: Optional field used in copy and move operations.
    :vartype from_property: str
    """

<<<<<<< HEAD
    _validation = {
        'op': {'required': True},
        'path': {'required': True},
    }

    _attribute_map = {
        'op': {'key': 'op', 'type': 'str'},
        'path': {'key': 'path', 'type': 'str'},
        'value': {'key': 'value', 'type': 'object'},
        'from_property': {'key': 'from', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword op: Required. The operation to be performed. Known values are: "add", "remove",
         "replace", "move", "copy", "test".
        :paramtype op: str or ~azure.quantum._client.models.JsonPatchOperation
        :keyword path: Required. A JSON-Pointer.
        :paramtype path: str
        :keyword value: A value to be used in the operation on the path.
        :paramtype value: any
        :keyword from_property: Optional field used in copy and move operations.
        :paramtype from_property: str
        """
        super(JsonPatchDocument, self).__init__(**kwargs)
        self.op = kwargs['op']
        self.path = kwargs['path']
        self.value = kwargs.get('value', None)
        self.from_property = kwargs.get('from_property', None)


class ProviderStatus(msrest.serialization.Model):
    """Providers status.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Provider id.
    :vartype id: str
    :ivar current_availability: Provider availability. Known values are: "Available", "Degraded",
     "Unavailable".
    :vartype current_availability: str or ~azure.quantum._client.models.ProviderAvailability
    :ivar targets:
    :vartype targets: list[~azure.quantum._client.models.TargetStatus]
    """

    _validation = {
        'id': {'readonly': True},
        'current_availability': {'readonly': True},
        'targets': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'current_availability': {'key': 'currentAvailability', 'type': 'str'},
        'targets': {'key': 'targets', 'type': '[TargetStatus]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        """
        super(ProviderStatus, self).__init__(**kwargs)
        self.id = None
        self.current_availability = None
        self.targets = None


class ProviderStatusList(msrest.serialization.Model):
    """Providers status.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar value:
    :vartype value: list[~azure.quantum._client.models.ProviderStatus]
    :ivar next_link: Link to the next page of results.
    :vartype next_link: str
    """

    _validation = {
        'value': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': '[ProviderStatus]'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        """
        super(ProviderStatusList, self).__init__(**kwargs)
        self.value = None
        self.next_link = None


class Quota(msrest.serialization.Model):
    """Quota information.

    :ivar dimension: The name of the dimension associated with the quota.
    :vartype dimension: str
    :ivar scope: The scope at which the quota is applied. Known values are: "Workspace",
     "Subscription".
    :vartype scope: str or ~azure.quantum._client.models.DimensionScope
    :ivar provider_id: The unique identifier for the provider.
    :vartype provider_id: str
    :ivar utilization: The amount of the usage that has been applied for the current period.
    :vartype utilization: float
    :ivar holds: The amount of the usage that has been reserved but not applied for the current
     period.
    :vartype holds: float
    :ivar limit: The maximum amount of usage allowed for the current period.
    :vartype limit: float
    :ivar period: The time period in which the quota's underlying meter is accumulated. Based on
     calendar year. 'None' is used for concurrent quotas. Known values are: "None", "Monthly".
    :vartype period: str or ~azure.quantum._client.models.MeterPeriod
    """

    _attribute_map = {
        'dimension': {'key': 'dimension', 'type': 'str'},
        'scope': {'key': 'scope', 'type': 'str'},
        'provider_id': {'key': 'providerId', 'type': 'str'},
        'utilization': {'key': 'utilization', 'type': 'float'},
        'holds': {'key': 'holds', 'type': 'float'},
        'limit': {'key': 'limit', 'type': 'float'},
        'period': {'key': 'period', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword dimension: The name of the dimension associated with the quota.
        :paramtype dimension: str
        :keyword scope: The scope at which the quota is applied. Known values are: "Workspace",
         "Subscription".
        :paramtype scope: str or ~azure.quantum._client.models.DimensionScope
        :keyword provider_id: The unique identifier for the provider.
        :paramtype provider_id: str
        :keyword utilization: The amount of the usage that has been applied for the current period.
        :paramtype utilization: float
        :keyword holds: The amount of the usage that has been reserved but not applied for the current
         period.
        :paramtype holds: float
        :keyword limit: The maximum amount of usage allowed for the current period.
        :paramtype limit: float
        :keyword period: The time period in which the quota's underlying meter is accumulated. Based on
         calendar year. 'None' is used for concurrent quotas. Known values are: "None", "Monthly".
        :paramtype period: str or ~azure.quantum._client.models.MeterPeriod
        """
        super(Quota, self).__init__(**kwargs)
        self.dimension = kwargs.get('dimension', None)
        self.scope = kwargs.get('scope', None)
        self.provider_id = kwargs.get('provider_id', None)
        self.utilization = kwargs.get('utilization', None)
        self.holds = kwargs.get('holds', None)
        self.limit = kwargs.get('limit', None)
        self.period = kwargs.get('period', None)


class QuotaList(msrest.serialization.Model):
    """List of quotas.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar value:
    :vartype value: list[~azure.quantum._client.models.Quota]
    :ivar next_link: Link to the next page of results.
    :vartype next_link: str
    """

    _validation = {
        'value': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': '[Quota]'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        """
        super(QuotaList, self).__init__(**kwargs)
        self.value = None
        self.next_link = None


class RestError(msrest.serialization.Model):
    """Error information returned by the API.

    :ivar error: An error response from Azure.
    :vartype error: ~azure.quantum._client.models.ErrorData
    """

    _attribute_map = {
        'error': {'key': 'error', 'type': 'ErrorData'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword error: An error response from Azure.
        :paramtype error: ~azure.quantum._client.models.ErrorData
        """
        super(RestError, self).__init__(**kwargs)
        self.error = kwargs.get('error', None)


class SasUriResponse(msrest.serialization.Model):
    """Get SAS URL operation response.

    :ivar sas_uri: A URL with a SAS token to upload a blob for execution in the given workspace.
    :vartype sas_uri: str
    """

    _attribute_map = {
        'sas_uri': {'key': 'sasUri', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword sas_uri: A URL with a SAS token to upload a blob for execution in the given workspace.
        :paramtype sas_uri: str
        """
        super(SasUriResponse, self).__init__(**kwargs)
        self.sas_uri = kwargs.get('sas_uri', None)


class TargetStatus(msrest.serialization.Model):
    """Target status.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Target id.
    :vartype id: str
    :ivar current_availability: Target availability. Known values are: "Available", "Degraded",
     "Unavailable".
    :vartype current_availability: str or ~azure.quantum._client.models.TargetAvailability
    :ivar average_queue_time: Average queue time in seconds.
    :vartype average_queue_time: long
=======
    operation: Union[str, "_models.JsonPatchOperation"] = rest_field(name="op", visibility=["create"])
    """The operation to be performed. Required. Known values are: \"add\", \"remove\", \"replace\",
     \"move\", \"copy\", and \"test\"."""
    path: str = rest_field(visibility=["create"])
    """A JSON-Pointer. Required."""
    value: Optional[Any] = rest_field(visibility=["create"])
    """A value to be used in the operation on the path."""
    from_property: Optional[str] = rest_field(name="from", visibility=["create"])
    """Optional field used in copy and move operations."""

    @overload
    def __init__(
        self,
        *,
        operation: Union[str, "_models.JsonPatchOperation"],
        path: str,
        value: Optional[Any] = None,
        from_property: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ProviderStatus(_model_base.Model):
    """Provider status.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar id: Provider id. Required.
    :vartype id: str
    :ivar current_availability: Current provider availability. Required. Known values are:
     "Available", "Degraded", and "Unavailable".
    :vartype current_availability: str or ~azure.quantum.models.ProviderAvailability
    :ivar targets: Current target statuses. Required.
    :vartype targets: list[~azure.quantum.models.TargetStatus]
    """

    id: str = rest_field(visibility=["read"])
    """Provider id. Required."""
    current_availability: Union[str, "_models.ProviderAvailability"] = rest_field(
        name="currentAvailability", visibility=["read"]
    )
    """Current provider availability. Required. Known values are: \"Available\", \"Degraded\", and
     \"Unavailable\"."""
    targets: List["_models.TargetStatus"] = rest_field(visibility=["read"])
    """Current target statuses. Required."""


class QuantumComputingData(_model_base.Model):
    """Quantum computing data.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar count: The number of quantum computing items in the job. Required.
    :vartype count: int
    """

    count: int = rest_field(visibility=["read"])
    """The number of quantum computing items in the job. Required."""


class Quota(_model_base.Model):
    """Quota information.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar dimension: The name of the dimension associated with the quota. Required.
    :vartype dimension: str
    :ivar scope: The scope at which the quota is applied. Required. Known values are: "Workspace"
     and "Subscription".
    :vartype scope: str or ~azure.quantum.models.DimensionScope
    :ivar provider_id: The unique identifier for the provider. Required.
    :vartype provider_id: str
    :ivar utilization: The amount of the usage that has been applied for the current period.
     Required.
    :vartype utilization: float
    :ivar holds: The amount of the usage that has been reserved but not applied for the current
     period. Required.
    :vartype holds: float
    :ivar limit: The maximum amount of usage allowed for the current period. Required.
    :vartype limit: float
    :ivar period: The time period in which the quota's underlying meter is accumulated. Based on
     calendar year. 'None' is used for concurrent quotas. Required. Known values are: "None" and
     "Monthly".
    :vartype period: str or ~azure.quantum.models.MeterPeriod
    """

    dimension: str = rest_field(visibility=["read"])
    """The name of the dimension associated with the quota. Required."""
    scope: Union[str, "_models.DimensionScope"] = rest_field(visibility=["read"])
    """The scope at which the quota is applied. Required. Known values are: \"Workspace\" and
     \"Subscription\"."""
    provider_id: str = rest_field(name="providerId", visibility=["read"])
    """The unique identifier for the provider. Required."""
    utilization: float = rest_field(visibility=["read"])
    """The amount of the usage that has been applied for the current period. Required."""
    holds: float = rest_field(visibility=["read"])
    """The amount of the usage that has been reserved but not applied for the current period.
     Required."""
    limit: float = rest_field(visibility=["read"])
    """The maximum amount of usage allowed for the current period. Required."""
    period: Union[str, "_models.MeterPeriod"] = rest_field(visibility=["read"])
    """The time period in which the quota's underlying meter is accumulated. Based on calendar year.
     'None' is used for concurrent quotas. Required. Known values are: \"None\" and \"Monthly\"."""


class SasUriResponse(_model_base.Model):
    """SAS URI operation response.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar sas_uri: A URL with a SAS token to upload a blob for execution in the given workspace.
     Required.
    :vartype sas_uri: str
    """

    sas_uri: str = rest_field(name="sasUri", visibility=["read"])
    """A URL with a SAS token to upload a blob for execution in the given workspace. Required."""


class SessionDetails(ItemDetails, discriminator="Session"):
    """Session, a logical grouping of jobs.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar name: The name of the item. It is not required for the name to be unique and it's only
     used for display purposes. Required.
    :vartype name: str
    :ivar provider_id: The unique identifier for the provider. Required.
    :vartype provider_id: str
    :ivar target: The target identifier to run the job. Required.
    :vartype target: str
    :ivar creation_time: The creation time of the item.
    :vartype creation_time: ~datetime.datetime
    :ivar begin_execution_time: The time when the item began execution.
    :vartype begin_execution_time: ~datetime.datetime
    :ivar end_execution_time: The time when the item finished execution.
    :vartype end_execution_time: ~datetime.datetime
    :ivar cost_estimate: Cost estimate.
    :vartype cost_estimate: ~azure.quantum.models.CostEstimate
    :ivar error_data: Error information.
    :vartype error_data: ~azure.quantum.models.WorkspaceItemError
    :ivar id: Id of the session. Required.
    :vartype id: str
    :ivar item_type: Type of the Quantum Workspace item is Session. Required. A logical grouping of
     jobs.
    :vartype item_type: str or ~azure.quantum.models.SESSION
    :ivar job_failure_policy: Policy controlling the behavior of the Session when a job in the
     session fails. Required. Known values are: "Abort" and "Continue".
    :vartype job_failure_policy: str or ~azure.quantum.models.SessionJobFailurePolicy
    :ivar status: The status of the session. Known values are: "Waiting", "Executing", "Succeeded",
     "Failed", "Failure(s)", and "TimedOut".
    :vartype status: str or ~azure.quantum.models.SessionStatus
    """

    item_type: Literal[ItemType.SESSION] = rest_discriminator(name="itemType", visibility=["read", "create"])  # type: ignore # pylint: disable=line-too-long
    """Type of the Quantum Workspace item is Session. Required. A logical grouping of jobs."""
    job_failure_policy: Union[str, "_models.SessionJobFailurePolicy"] = rest_field(
        name="jobFailurePolicy", visibility=["read", "create"]
    )
    """Policy controlling the behavior of the Session when a job in the session fails. Required. Known
     values are: \"Abort\" and \"Continue\"."""
    status: Optional[Union[str, "_models.SessionStatus"]] = rest_field(visibility=["read"])
    """The status of the session. Known values are: \"Waiting\", \"Executing\", \"Succeeded\",
     \"Failed\", \"Failure(s)\", and \"TimedOut\"."""

    @overload
    def __init__(
        self,
        *,
        name: str,
        provider_id: str,
        target: str,
        job_failure_policy: Union[str, "_models.SessionJobFailurePolicy"],
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, item_type=ItemType.SESSION, **kwargs)


class TargetStatus(_model_base.Model):
    """Target status.

    Readonly variables are only populated by the server, and will be ignored when sending a request.


    :ivar id: Target id. Required.
    :vartype id: str
    :ivar current_availability: Current target availability. Required. Known values are:
     "Available", "Degraded", and "Unavailable".
    :vartype current_availability: str or ~azure.quantum.models.TargetAvailability
    :ivar average_queue_time: Average queue time in seconds. Required.
    :vartype average_queue_time: int
>>>>>>> upstream/main
    :ivar status_page: A page with detailed status of the provider.
    :vartype status_page: str
    """

<<<<<<< HEAD
    _validation = {
        'id': {'readonly': True},
        'current_availability': {'readonly': True},
        'average_queue_time': {'readonly': True},
        'status_page': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'current_availability': {'key': 'currentAvailability', 'type': 'str'},
        'average_queue_time': {'key': 'averageQueueTime', 'type': 'long'},
        'status_page': {'key': 'statusPage', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        """
        super(TargetStatus, self).__init__(**kwargs)
        self.id = None
        self.current_availability = None
        self.average_queue_time = None
        self.status_page = None


class UsageEvent(msrest.serialization.Model):
    """Usage event details.

    :ivar dimension_id: The dimension id.
    :vartype dimension_id: str
    :ivar dimension_name: The dimension name.
    :vartype dimension_name: str
    :ivar measure_unit: The unit of measure.
    :vartype measure_unit: str
    :ivar amount_billed: The amount billed.
    :vartype amount_billed: float
    :ivar amount_consumed: The amount consumed.
    :vartype amount_consumed: float
    :ivar unit_price: The unit price.
    :vartype unit_price: float
    """

    _attribute_map = {
        'dimension_id': {'key': 'dimensionId', 'type': 'str'},
        'dimension_name': {'key': 'dimensionName', 'type': 'str'},
        'measure_unit': {'key': 'measureUnit', 'type': 'str'},
        'amount_billed': {'key': 'amountBilled', 'type': 'float'},
        'amount_consumed': {'key': 'amountConsumed', 'type': 'float'},
        'unit_price': {'key': 'unitPrice', 'type': 'float'},
    }

    def __init__(
        self,
        **kwargs
    ):
        """
        :keyword dimension_id: The dimension id.
        :paramtype dimension_id: str
        :keyword dimension_name: The dimension name.
        :paramtype dimension_name: str
        :keyword measure_unit: The unit of measure.
        :paramtype measure_unit: str
        :keyword amount_billed: The amount billed.
        :paramtype amount_billed: float
        :keyword amount_consumed: The amount consumed.
        :paramtype amount_consumed: float
        :keyword unit_price: The unit price.
        :paramtype unit_price: float
        """
        super(UsageEvent, self).__init__(**kwargs)
        self.dimension_id = kwargs.get('dimension_id', None)
        self.dimension_name = kwargs.get('dimension_name', None)
        self.measure_unit = kwargs.get('measure_unit', None)
        self.amount_billed = kwargs.get('amount_billed', None)
        self.amount_consumed = kwargs.get('amount_consumed', None)
        self.unit_price = kwargs.get('unit_price', None)
=======
    id: str = rest_field(visibility=["read"])
    """Target id. Required."""
    current_availability: Union[str, "_models.TargetAvailability"] = rest_field(
        name="currentAvailability", visibility=["read"]
    )
    """Current target availability. Required. Known values are: \"Available\", \"Degraded\", and
     \"Unavailable\"."""
    average_queue_time: int = rest_field(name="averageQueueTime", visibility=["read"])
    """Average queue time in seconds. Required."""
    status_page: Optional[str] = rest_field(name="statusPage", visibility=["read"])
    """A page with detailed status of the provider."""


class UsageEvent(_model_base.Model):
    """Usage event details.


    :ivar dimension_id: The dimension id. Required.
    :vartype dimension_id: str
    :ivar dimension_name: The dimension name. Required.
    :vartype dimension_name: str
    :ivar measure_unit: The unit of measure. Required.
    :vartype measure_unit: str
    :ivar amount_billed: The amount billed. Required.
    :vartype amount_billed: float
    :ivar amount_consumed: The amount consumed. Required.
    :vartype amount_consumed: float
    :ivar unit_price: The unit price. Required.
    :vartype unit_price: float
    """

    dimension_id: str = rest_field(name="dimensionId")
    """The dimension id. Required."""
    dimension_name: str = rest_field(name="dimensionName")
    """The dimension name. Required."""
    measure_unit: str = rest_field(name="measureUnit")
    """The unit of measure. Required."""
    amount_billed: float = rest_field(name="amountBilled")
    """The amount billed. Required."""
    amount_consumed: float = rest_field(name="amountConsumed")
    """The amount consumed. Required."""
    unit_price: float = rest_field(name="unitPrice")
    """The unit price. Required."""

    @overload
    def __init__(
        self,
        *,
        dimension_id: str,
        dimension_name: str,
        measure_unit: str,
        amount_billed: float,
        amount_consumed: float,
        unit_price: float,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class WorkspaceItemError(_model_base.Model):
    """The error object.


    :ivar code: One of a server-defined set of error codes. Required.
    :vartype code: str
    :ivar message: A human-readable representation of the error. Required.
    :vartype message: str
    :ivar target: The target of the error.
    :vartype target: str
    :ivar details: An array of details about specific errors that led to this reported error.
    :vartype details: list[~azure.core.ODataV4Format]
    :ivar innererror: An object containing more specific information than the current object about
     the error.
    :vartype innererror: ~azure.quantum.models.InnerError
    """

    code: str = rest_field()
    """One of a server-defined set of error codes. Required."""
    message: str = rest_field()
    """A human-readable representation of the error. Required."""
    target: Optional[str] = rest_field()
    """The target of the error."""
    details: Optional[List[ODataV4Format]] = rest_field()
    """An array of details about specific errors that led to this reported error."""
    innererror: Optional["_models.InnerError"] = rest_field()
    """An object containing more specific information than the current object about the error."""

    @overload
    def __init__(
        self,
        *,
        code: str,
        message: str,
        target: Optional[str] = None,
        details: Optional[List[ODataV4Format]] = None,
        innererror: Optional["_models.InnerError"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
>>>>>>> upstream/main
